#!/bin/bash

# SCRIPT = $0 might work 
ME=$(readlink -f $0 2> /dev/null)
if [[ $ME == "" ]]
then
   # MacOS doesn't support -f for readlink
   ME=$0
fi
# Absolute path this script is in, thus /home/user/bin
DIR=$(dirname $ME)

# class path is
#  $DIR/../oriented*.jar
#  $DIR/../lib/*.jar

CP=`echo $DIR/../oriented*.jar`
CP=$CP:$DIR/../bin

CP=$CP`(cd $DIR/../lib ;
   ls -1 | awk '{ printf ":'"$DIR"'/../lib/%s", $0 }' )`

echo $CP
java -classpath $CP oriented.Image $*
